//
//  LoopInsights_TestDataProvider.swift
//  Loop
//
//  Concept & design by Taylor Patterson. Coded & tested by Claude Code in February 2026.
//  Copyright (c) 2025-2026 LoopKit Authors. All rights reserved.
//

import Foundation
import LoopKit
import HealthKit

/// Loads JSON fixture files (generated by pull_tidepool_data.py) and provides them
/// to LoopInsights as if they came from the real Loop data stores.
///
/// File lookup order:
/// 1. App's Documents/LoopInsights/ directory (user-provided, no rebuild needed)
/// 2. App bundle Resources/LoopInsights/TestData/ (developer-bundled)
///
/// Expected fixture filenames:
/// - tidepool_glucose_samples.json
/// - tidepool_dose_entries.json
/// - tidepool_carb_entries.json
/// - tidepool_therapy_settings.json (optional)
final class LoopInsights_TestDataProvider: LoopInsightsDataProviderProtocol {

    // MARK: - Cached Data

    private var glucoseSamples: [StoredGlucoseSample] = []
    private var carbEntries: [StoredCarbEntry] = []
    private var doseEntries: [DoseEntry] = []
    private var storedSettings: StoredSettings = StoredSettings()

    private var isLoaded = false

    // MARK: - File Names

    private enum FixtureFile {
        static let glucose = "tidepool_glucose_samples.json"
        static let doses = "tidepool_dose_entries.json"
        static let carbs = "tidepool_carb_entries.json"
        static let settings = "tidepool_therapy_settings.json"
    }

    // MARK: - Initialization

    init() {
        loadFixtures()
    }

    // MARK: - Data Availability

    /// Returns true if any test data fixtures were found and loaded.
    var hasTestData: Bool {
        return !glucoseSamples.isEmpty || !doseEntries.isEmpty || !carbEntries.isEmpty
    }

    /// Summary of loaded fixture data.
    var dataSummary: String {
        return "Glucose: \(glucoseSamples.count), Doses: \(doseEntries.count), Carbs: \(carbEntries.count)"
    }

    /// Date range of the loaded data (nil if empty).
    var dateRange: (start: Date, end: Date)? {
        var allDates: [Date] = []
        allDates.append(contentsOf: glucoseSamples.map { $0.startDate })
        allDates.append(contentsOf: doseEntries.map { $0.startDate })
        allDates.append(contentsOf: carbEntries.map { $0.startDate })

        guard let earliest = allDates.min(), let latest = allDates.max() else {
            return nil
        }
        return (earliest, latest)
    }

    // MARK: - LoopInsightsDataProviderProtocol

    func getGlucoseSamples(start: Date, end: Date) async throws -> [StoredGlucoseSample] {
        return glucoseSamples.filter { $0.startDate >= start && $0.startDate <= end }
    }

    func getCarbEntries(start: Date, end: Date) async throws -> [StoredCarbEntry] {
        return carbEntries.filter { $0.startDate >= start && $0.startDate <= end }
    }

    func getNormalizedDoseEntries(start: Date, end: Date) async throws -> [DoseEntry] {
        return doseEntries.filter { $0.startDate >= start && $0.startDate <= end }
    }

    func getLatestStoredSettings() -> StoredSettings {
        return storedSettings
    }

    // MARK: - Static Helpers

    /// Check if test data fixtures exist in any search location.
    static var fixturesAvailable: Bool {
        return resolveFixturePath(for: FixtureFile.glucose) != nil ||
               resolveFixturePath(for: FixtureFile.doses) != nil ||
               resolveFixturePath(for: FixtureFile.carbs) != nil
    }

    /// Returns the Documents/LoopInsights/ directory path (creates it if needed).
    static var documentsDirectory: URL {
        let docs = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first
            ?? URL(fileURLWithPath: NSHomeDirectory())
        let dir = docs.appendingPathComponent("LoopInsights", isDirectory: true)
        try? FileManager.default.createDirectory(at: dir, withIntermediateDirectories: true)
        return dir
    }

    // MARK: - Private Loading

    private func loadFixtures() {
        guard !isLoaded else { return }
        isLoaded = true

        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .custom { decoder in
            let container = try decoder.singleValueContainer()
            let dateString = try container.decode(String.self)
            if let date = Self.iso8601Formatter.date(from: dateString) {
                return date
            }
            if let date = Self.iso8601FractionalFormatter.date(from: dateString) {
                return date
            }
            throw DecodingError.dataCorruptedError(in: container, debugDescription: "Cannot parse date: \(dateString)")
        }

        // Load glucose samples
        if let data = Self.loadFixtureData(for: FixtureFile.glucose) {
            do {
                glucoseSamples = try decoder.decode([StoredGlucoseSample].self, from: data)
                LoopInsights_FeatureFlags.log.debug("TestData: Loaded \(self.glucoseSamples.count) glucose samples")
            } catch {
                LoopInsights_FeatureFlags.log.error("TestData: Failed to decode glucose: \(error)")
            }
        }

        // Load dose entries (pre-process to strip scheduledBasalRate fields that crash HKUnit)
        if let data = Self.loadFixtureData(for: FixtureFile.doses) {
            let sanitizedData = Self.sanitizeDoseJSON(data)
            do {
                doseEntries = try decoder.decode([DoseEntry].self, from: sanitizedData)
                LoopInsights_FeatureFlags.log.debug("TestData: Loaded \(self.doseEntries.count) dose entries")
            } catch {
                LoopInsights_FeatureFlags.log.error("TestData: Failed to decode doses: \(error)")
            }
        }

        // Load carb entries
        if let data = Self.loadFixtureData(for: FixtureFile.carbs) {
            do {
                carbEntries = try decoder.decode([StoredCarbEntry].self, from: data)
                LoopInsights_FeatureFlags.log.debug("TestData: Loaded \(self.carbEntries.count) carb entries")
            } catch {
                LoopInsights_FeatureFlags.log.error("TestData: Failed to decode carbs: \(error)")
            }
        }

        // Load therapy settings (optional — builds StoredSettings from Tidepool schedule data)
        if let data = Self.loadFixtureData(for: FixtureFile.settings) {
            loadTherapySettings(data: data)
        }
    }

    /// Parse the Tidepool therapy settings JSON and construct a StoredSettings instance.
    private func loadTherapySettings(data: Data) {
        guard let json = try? JSONSerialization.jsonObject(with: data) as? [String: Any] else {
            LoopInsights_FeatureFlags.log.error("TestData: Failed to parse therapy settings JSON")
            return
        }

        var basalSchedule: BasalRateSchedule?
        var isfSchedule: InsulinSensitivitySchedule?
        var crSchedule: CarbRatioSchedule?

        // Basal rate schedule
        if let items = json["basalRateSchedule"] as? [[String: Any]] {
            let dailyItems = items.compactMap { item -> RepeatingScheduleValue<Double>? in
                guard let startTime = item["startTime"] as? Double,
                      let value = item["value"] as? Double else { return nil }
                return RepeatingScheduleValue(startTime: startTime, value: value)
            }
            if !dailyItems.isEmpty {
                basalSchedule = DailyValueSchedule(dailyItems: dailyItems)
            }
        }

        // Insulin sensitivity schedule (mg/dL)
        if let items = json["insulinSensitivitySchedule"] as? [[String: Any]] {
            let dailyItems = items.compactMap { item -> RepeatingScheduleValue<Double>? in
                guard let startTime = item["startTime"] as? Double,
                      let value = item["value"] as? Double else { return nil }
                return RepeatingScheduleValue(startTime: startTime, value: value)
            }
            if !dailyItems.isEmpty {
                isfSchedule = DailyQuantitySchedule(unit: .milligramsPerDeciliter, dailyItems: dailyItems)
            }
        }

        // Carb ratio schedule (g/U)
        if let items = json["carbRatioSchedule"] as? [[String: Any]] {
            let dailyItems = items.compactMap { item -> RepeatingScheduleValue<Double>? in
                guard let startTime = item["startTime"] as? Double,
                      let value = item["value"] as? Double else { return nil }
                return RepeatingScheduleValue(startTime: startTime, value: value)
            }
            if !dailyItems.isEmpty {
                crSchedule = DailyQuantitySchedule(unit: .gram(), dailyItems: dailyItems)
            }
        }

        storedSettings = StoredSettings(
            dosingEnabled: true,
            basalRateSchedule: basalSchedule,
            insulinSensitivitySchedule: isfSchedule,
            carbRatioSchedule: crSchedule
        )
        LoopInsights_FeatureFlags.log.debug("TestData: Loaded therapy settings (basal: \(basalSchedule?.items.count ?? 0), ISF: \(isfSchedule?.items.count ?? 0), CR: \(crSchedule?.items.count ?? 0))")
    }

    // MARK: - Dose JSON Sanitization

    /// Remove scheduledBasalRate/scheduledBasalRateUnit from dose JSON to prevent
    /// HKUnit(from:) NSException crashes with non-standard unit strings.
    /// LoopInsights only needs type, startDate, endDate, value, unit, deliveredUnits, automatic.
    private static func sanitizeDoseJSON(_ data: Data) -> Data {
        guard var jsonArray = try? JSONSerialization.jsonObject(with: data) as? [[String: Any]] else {
            return data
        }
        for i in jsonArray.indices {
            jsonArray[i].removeValue(forKey: "scheduledBasalRate")
            jsonArray[i].removeValue(forKey: "scheduledBasalRateUnit")
        }
        return (try? JSONSerialization.data(withJSONObject: jsonArray)) ?? data
    }

    // MARK: - File Resolution

    /// Find the path to a fixture file, checking Documents first, then bundle.
    private static func resolveFixturePath(for filename: String) -> URL? {
        // 1. Check Documents/LoopInsights/
        let docsPath = documentsDirectory.appendingPathComponent(filename)
        if FileManager.default.fileExists(atPath: docsPath.path) {
            return docsPath
        }

        // 2. Check app bundle
        let name = (filename as NSString).deletingPathExtension
        let ext = (filename as NSString).pathExtension
        if let bundlePath = Bundle.main.url(forResource: name, withExtension: ext, subdirectory: "LoopInsights/TestData") {
            return bundlePath
        }

        // 3. Check bundle root (flat resources)
        if let bundlePath = Bundle.main.url(forResource: name, withExtension: ext) {
            return bundlePath
        }

        return nil
    }

    /// Load raw Data from a fixture file.
    private static func loadFixtureData(for filename: String) -> Data? {
        guard let url = resolveFixturePath(for: filename) else {
            LoopInsights_FeatureFlags.log.error("TestData: Fixture not found: \(filename)")
            return nil
        }
        LoopInsights_FeatureFlags.log.debug("TestData: Loading \(url.lastPathComponent) from \(url.deletingLastPathComponent().lastPathComponent)/")
        return try? Data(contentsOf: url)
    }

    // MARK: - Date Formatters

    /// ISO 8601 without fractional seconds: "2026-02-10T12:00:00Z"
    private static let iso8601Formatter: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime]
        return f
    }()

    /// ISO 8601 with fractional seconds: "2026-02-10T12:00:00.000Z"
    private static let iso8601FractionalFormatter: ISO8601DateFormatter = {
        let f = ISO8601DateFormatter()
        f.formatOptions = [.withInternetDateTime, .withFractionalSeconds]
        return f
    }()
}
