name: Build Loop IPA

on:
  workflow_dispatch:
  push:
    branches: [ dev, main ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build IPA
        run: |
          xcodebuild archive -workspace Loop.xcworkspace -scheme Loop -archivePath build/Loop.xcarchive
          xcodebuild -exportArchive -archivePath build/Loop.xcarchive -exportOptionsPlist ExportOptions.plist -exportPath ./output

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Loop安装包
          path: ./output/*.ipa
